// AUTH
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_ERRORS = 'SET_ERRORS'

// SOCKET
export const SOCKET_INIT = 'SOCKET_INIT'

// CHAT
export const TOGGLE_CHAT = 'TOGGLE_CHAT'
export const SET_USERS = 'SET_USERS'
export const GET_MESSAGES = 'GET_MESSAGES'
export const SAVE_MESSAGE = 'SAVE_MESSAGE'
export const EMAIL_CHAT_HISTORY = 'EMAIL_CHAT_HISTORY'
export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE'
export const GET_ROOM_USERS = 'GET_ROOM_USERS'


// LOCATION
export const SET_LOCATION = 'SET_LOCATION'
export const GET_LOCATIONS = 'GET_LOCATIONS'

// TODO
export const ADD_TODO = 'ADD_TODO'
export const GET_TODOS = 'GET_TODOS'
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE'
export const SORT_USER_TODOS = 'SORT_USER_TODOS'
export const SORT_STATUS_TODOS = 'SORT_STATUS_TODOS'
export const SORT_PRIORITY_TODOS = 'SORT_PRIORITY_TODOS'

// REMINDER
export const ADD_REMINDER = 'ADD_REMINDER'
export const GET_REMINDERS = 'GET_REMINDERS'

// LOADING
export const LOADING = 'LOADING'




