module.exports = {
	USER_CONNECTED:"USER_CONNECTED",
	UPDATE_USER_LIST:"UPDATE_USER_LIST",
  NEW_MESSAGE:"NEW_MESSAGE",
  MESSAGE_SENT:"MESSAGE_SENT",
  CLIENT_DISCONNECTED:"CLIENT_DISCONNECTED",
  JOIN:"JOIN",
  MARK_AS_READ:"MARK_AS_READ",
  MARK_AS_READED:"MARK_AS_READED",
  ASK_PERMISION:"ASK_PERMISION",
  PERMISION_TO_DELETE:"PERMISION_TO_DELETE",
  REPLY_TO_DELETE:"REPLY_TO_DELETE",
  CONFIRM_DELETE:"CONFIRM_DELETE",
  REMOVE_IMPORTANT:"REMOVE_IMPORTANT",
  REMOVED_IMPORTANT:"REMOVED_IMPORTANT",
  CHAT_STATUS:"CHAT_STATUS",
  CHAT_STAT:"CHAT_STAT",
  UPDATE_UNREAD_COUNT:"UPDATE_UNREAD_COUNT",
  UNREAD_COUNT_UPDATED:"UNREAD_COUNT_UPDATED",
  
  
}