module.exports = {
	USER_CONNECTED:"USER_CONNECTED",
	UPDATE_USER_LIST:"UPDATE_USER_LIST",
  NEW_MESSAGE:"NEW_MESSAGE",
  MESSAGE_SENT:"MESSAGE_SENT",
  CLIENT_DISCONNECTED:"CLIENT_DISCONNECTED",
  JOIN:"JOIN"
}