module.exports = {
  // CHAT
	USER_CONNECTED:"USER_CONNECTED",
	UPDATE_USER_LIST:"UPDATE_USER_LIST",
  NEW_MESSAGE:"NEW_MESSAGE",
  MESSAGE_SENT:"MESSAGE_SENT",
  CLIENT_DISCONNECTED:"CLIENT_DISCONNECTED",
  JOIN:"JOIN",
  MARK_AS_READ:"MARK_AS_READ",
  MARK_AS_READED:"MARK_AS_READED",
  ASK_PERMISION:"ASK_PERMISION",
  PERMISION_TO_DELETE:"PERMISION_TO_DELETE",
  REPLY_TO_DELETE:"REPLY_TO_DELETE",
  CONFIRM_DELETE:"CONFIRM_DELETE",
  REMOVE_IMPORTANT:"REMOVE_IMPORTANT",
  REMOVED_IMPORTANT:"REMOVED_IMPORTANT",
  CHAT_STATUS:"CHAT_STATUS",
  CHAT_STAT:"CHAT_STAT",
  UPDATE_OWN_UNREAD_COUNT:"UPDATE_OWN_UNREAD_COUNT",
  UPDATE_PARTNER_UNREAD_COUNT:"UPDATE_PARTNER_UNREAD_COUNT",
  UNREAD_COUNT_UPDATED:"UNREAD_COUNT_UPDATED",
  UPDATE_PARTNER_IMPORTANT_COUNT:"UPDATE_PARTNER_IMPORTANT_COUNT",  
  IMPORTANT_COUNT_UPDATED:"IMPORTANT_COUNT_UPDATED",
  TYPING:"TYPING",
  TYPING_USER:"TYPING_USER",
  
  // LOCATION
  SHARE_LOCATION:"SHARE_LOCATION",
  LOCATION_SHARED:"LOCATION_SHARED",

  
  // TODOS
  TODO_ADD:"TODO_ADD",
  TODO_ADDED:"TODO_ADDED",
  TODOS_UPDATE:"TODOS_UPDATE",
  TODOS_UPDATED:"TODOS_UPDATED",
  
  // REMINDERS
  REMINDER_ADD:"REMINDER_ADD",
  REMINDER_ADDED:"REMINDER_ADDED",
  REMINDERS_UPDATE:"REMINDERS_UPDATE",
  REMINDERS_UPDATED:"REMINDERS_UPDATED"

}